### ISSUE TITLE
上传iOS证书之后，证书列表打不开了，后台服务报错

### ISSUE THREAD

**Issue by dumingxin** [FlowCI/flow-platform#238]
错误信息
```code
Caused by: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (7864712 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.
flow.ci_1   | 	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3678)
flow.ci_1   | 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2509)
flow.ci_1   | 	at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1281)
flow.ci_1   | 	at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:782)
flow.ci_1   | 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
flow.ci_1   | 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
flow.ci_1   | 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
flow.ci_1   | 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
flow.ci_1   | 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
flow.ci_1   | 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
flow.ci_1   | 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:205)
flow.ci_1   | 	... 67 more

```

**Comment by yang-guo-2016** [comment]
@dumingxin 是 p12 和 mobileprovisiton 都上传了嘛？ 证书大小是多少

**Comment by dumingxin** [comment]
iOS证书大小应该都差不多吧，今天iOS开发的同事没在，所以暂时提供不了

**Comment by yunheli** [comment]
@dumingxin 临时解决方案，进入docker 修改 /var/lib/mysql/conf.d/mysqld.cnf
添加 max_allowed_packet=32M

**Comment by yunheli** [comment]
@dumingxin 下版我们会加上

**Comment by yunheli** [comment]
@dumingxin 请问是docker中的最新代码么？因为最新代码中mysql的 max_allowed_packet 默认是 16M上传应该没问题，更新下代码再试试

**Comment by yunheli** [comment]
@dumingxin  方便留个联系方式么？ 或者 +群： 154788427
