### ISSUE TITLE
Error: Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by wfxphoebus** [FlowCI/flow-platform#297]
git clone -b master https://github.com/FlowCI/flow-web.git
cd flow-web
export NODE_ENV=production
export FLOW_WEB_API="http://your_flow_api_url"
npm run compile

运行之后出现这个错误

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Well/temp/flow-web/build/scripts/compile.js:1:74)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)

**Comment by yang-guo-2016** [comment]
@wfxphoebus 可以用 `npm install --save fs-extra` 先把这个 module 安装上再试试看
