### ISSUE TITLE
正常启动，但是一开始构建就报错

### ISSUE THREAD

**Issue by sdaduanbilei** [FlowCI/flow-platform#307]
```java
flow.ci_1   | java.lang.NullPointerException
flow.ci_1   | 	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
flow.ci_1   | 	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
flow.ci_1   | 	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
flow.ci_1   | 	at java.nio.file.Paths.get(Paths.java:84)
flow.ci_1   | 	at com.flow.platform.cc.controller.CmdController.downloadFullLog(CmdController.java:156)
flow.ci_1   | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
flow.ci_1   | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
flow.ci_1   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
flow.ci_1   | 	at java.lang.reflect.Method.invoke(Method.java:498)
flow.ci_1   | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
flow.ci_1   | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
flow.ci_1   | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
flow.ci_1   | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
flow.ci_1   | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
flow.ci_1   | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
flow.ci_1   | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
flow.ci_1   | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
flow.ci_1   | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
flow.ci_1   | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
flow.ci_1   | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
flow.ci_1   | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
flow.ci_1   | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
flow.ci_1   | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
flow.ci_1   | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
flow.ci_1   | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
flow.ci_1   | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
flow.ci_1   | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
flow.ci_1   | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
flow.ci_1   | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
flow.ci_1   | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
flow.ci_1   | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
flow.ci_1   | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
flow.ci_1   | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
flow.ci_1   | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
flow.ci_1   | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
flow.ci_1   | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
flow.ci_1   | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
flow.ci_1   | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
flow.ci_1   | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
flow.ci_1   | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
flow.ci_1   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
flow.ci_1   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
flow.ci_1   | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
flow.ci_1   | 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by yunheli** [comment]
@sdaduanbilei  agent的报的错么？最新的代码么？系统是什么？

**Comment by sdaduanbilei** [comment]
agent 之前是正常的 我nohup 启动了  ，奇怪的问题就是 我重启后，agent 会自启动，并且 系统设置无法关闭，代码是最新的 昨天从docker 拉取的
系统信息
```                                     sdaduanbilei@jenkins
         eeeeeeeeeeeeeeeee           OS: elementary OS 0.4.1 loki
      eeeeeeeeeeeeeeeeeeeeeee        Kernel: x86_64 Linux 4.4.0-91-generic
    eeeee  eeeeeeeeeeee   eeeee      Uptime: 43m
  eeee   eeeee       eee     eeee    Packages: 2739
 eeee   eeee          eee     eeee   Shell: zsh l
eee    eee            eee       eee  Resolution: 1920x1080
eee   eee            eee        eee  WM: Mutter(DeepinGala)
ee    eee           eeee       eeee  WM Theme: Numix Daily
ee    eee         eeeee      eeeeee  CPU: Intel Core i3-4160 CPU @ 3.6GHz
ee    eee       eeeee      eeeee ee  RAM: 3194MiB / 15947MiB
eee   eeee   eeeeee      eeeee  eee 
eee    eeeeeeeeee     eeeeee    eee 
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee  
  eeeeeeee eeeeeeeeeeee      eeee   
    eeeee                 eeeee     
      eeeeeee         eeeeeee       
         eeeeeeeeeeeeeeeee   
````

**Comment by yunheli** [comment]
@sdaduanbilei  你把agent手动kill掉试试，再启动试试

**Comment by sdaduanbilei** [comment]
@yunheli 手动kill后，重启agent 后正常！是系统设置端的停止无法作用？

**Comment by yunheli** [comment]
@sdaduanbilei 现在还报错么？

**Comment by sdaduanbilei** [comment]
可以了，我关闭！谢谢 @yunheli

**Comment by yunheli** [comment]
@sdaduanbilei 重新拉取代码后，agent要重启，agent可能有更新
