### ISSUE TITLE
Agent 无法启动

### ISSUE THREAD

**Issue by sdaduanbilei** [FlowCI/flow-platform#308]
错误信息如下
```
2018-04-13 11:12:32.641 [ERROR] App - Cannot load agent config from zone
java.lang.IllegalStateException: Unable to load agent setting with http status -1
	at com.flow.platform.agent.Config.loadAgentConfig(Config.java:190)
	at com.flow.platform.agent.App.main(App.java:54)
```

**Comment by yunheli** [comment]
@sdaduanbilei 怎么启动的agent

**Comment by yunheli** [comment]
把启动server和agent的命令贴一下

**Comment by sdaduanbilei** [comment]
@yunheli 
```
###################Start Agent Using jar#######################
nohup:   _____ _             _           _    _____                             
 / ____| |           | |         | |  / ____|                            
| (___ | |_ __ _ _ __| |_ ___  __| | | (___  _   _  ___ ___ ___  ___ ___ 
 \___ \| __/ _` | '__| __/ _ \/ _` |  \___ \| | | |/ __/ __/ _ \/ __/ __|
 ____) | || (_| | |  | ||  __/ (_| |  ____) | |_| | (_| (_|  __/\__ \__ \
|_____/ \__\__,_|_|   \__\___|\__,_| |_____/ \__,_|\___\___\___||___/___/


把输出追加到'nohup.out'
```

```
java -jar flow-agent-v0.1.4-alpha.jar http:10.1.250.31:8082/flow-api 5c5758d4-8f28-4a44-9fcd-14f70ee02ce3
```
